# Generated by Django 3.0.6 on 2020-06-03 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('support', '0001_initial'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceivedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_received', models.DateField(auto_now=True)),
                ('quantity', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Item')),
                ('project', models.ManyToManyField(to='support.Project')),
            ],
        ),
        migrations.CreateModel(
            name='IssuedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_date', models.DateField(auto_now=True)),
                ('quantity', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Item')),
                ('requestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='support.Requestor')),
                ('work', models.ManyToManyField(to='support.Work')),
            ],
        ),
        migrations.CreateModel(
            name='BalanceItemQuantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ManyToManyField(to='support.Project')),
            ],
        ),
    ]
