# Generated by Django 3.0.6 on 2020-06-10 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balanceitemquantity',
            name='project',
        ),
    ]
