# Generated by Django 3.0.6 on 2020-06-10 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20200610_2330'),
        ('inventory', '0002_remove_balanceitemquantity_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='balanceitemquantity',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Item'),
        ),
    ]
