# Generated by Django 3.0.6 on 2020-06-10 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20200610_2330'),
        ('inventory', '0003_balanceitemquantity_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balanceitemquantity',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Item'),
        ),
    ]
