# Generated by Django 3.0.6 on 2020-06-11 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20200610_2330'),
        ('inventory', '0004_auto_20200611_0112'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='balanceitemquantity',
            options={'ordering': ['-item__item_id']},
        ),
        migrations.AlterField(
            model_name='balanceitemquantity',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Item'),
        ),
    ]
