# Generated by Django 3.0.6 on 2020-06-03 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='main_category',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='location',
            name='location_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shelf',
            name='shelf_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
