# Generated by Django 3.0.6 on 2020-06-10 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_auto_20200603_1711'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
