# Generated by Django 3.0.6 on 2020-06-10 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_delete_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='hod',
            field=models.CharField(default=1, max_length=50),
        ),
    ]
