# Generated by Django 3.0.6 on 2020-06-25 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0004_department_hod'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
