# Generated by Django 3.0.6 on 2020-06-25 00:43

from django.db import migrations
from django.utils.text import slugify

def slugify_name(apps, schema_editor):
    Project = apps.get_model('support', 'Project')
    for project in Project.objects.all():
        project.slug = slugify(project.name)
        project.save()


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0005_project_slug'),
    ]

    operations = [
        migrations.RunPython(slugify_name),
    ]
