# Generated by Django 3.0.6 on 2020-06-03 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('item_id', models.CharField(blank=True, max_length=20, null=True)),
                ('category', models.ManyToManyField(to='support.Category')),
                ('location', models.ManyToManyField(to='support.Location')),
                ('shelve_label', models.ManyToManyField(to='support.Shelf')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
    ]
