# Generated by Django 3.0.6 on 2020-06-03 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_auto_20200603_1711'),
        ('main', '0002_itemimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='shelve_label',
            field=models.ManyToManyField(blank=True, null=True, to='support.Shelf'),
        ),
    ]
