# Generated by Django 3.0.6 on 2020-06-10 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200603_1714'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('-item_id',)},
        ),
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
    ]
