# Generated by Django 3.0.6 on 2020-06-10 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_delete_category'),
        ('main', '0004_auto_20200610_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='shelve_label',
            field=models.ManyToManyField(blank=True, to='support.Shelf'),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_category', models.CharField(max_length=100)),
                ('sub_category', models.CharField(blank=True, max_length=100, null=True)),
                ('category_summary', models.TextField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Item')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ('item',),
            },
        ),
    ]
