# Generated by Django 3.0.6 on 2020-06-10 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200610_2049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='main_category',
            new_name='category_name',
        ),
        migrations.AddField(
            model_name='category',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
