# Generated by Django 3.0.6 on 2020-06-10 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200610_2114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_name',
            new_name='catname',
        ),
    ]
