# Generated by Django 3.0.6 on 2020-06-10 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_category_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_slug',
            field=models.CharField(default=1, max_length=100),
        ),
    ]
