# Generated by Django 3.0.6 on 2020-06-23 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20200623_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='sub_category',
            field=models.CharField(default=1, max_length=50),
        ),
    ]
