# Generated by Django 3.0.6 on 2020-06-23 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_item_sub_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='unit',
            field=models.CharField(default=1, max_length=50),
        ),
    ]
